### ISSUE TITLE
使用项目分析libcms.so出现问题

### ISSUE THREAD

**Issue by oMengLvRong** [maiyao1988/deobf#1]
错误如下，测试的是某视频app的libcms.so，尝试使用项目简化JNI_Onload： 
assert size > 0, "block %r size <=0"%b
AssertionError: block CodeBlock(0x00004E5E, 0x00000000) size <=0

**Comment by maiyao1988** [comment]
CMS是这个仓库里面的吗,JNI_ONLoad的start 和 end 是0x0007942C 0x0007CC3E吗，如果是其他cms，麻烦提供一下so

**Comment by oMengLvRong** [comment]
链接：https://pan.baidu.com/s/19EZ3WGpLkBz-yQNatVSLxQ 
提取码：s61v

参考JNI_ONLoad的start 和 end是 0x00004D8C 0x00004EF0

**Comment by maiyao1988** [comment]
我看了一下，这个混淆跟之前的cms混淆有所改变，需要时间分析一下

**Comment by maiyao1988** [comment]
出错的直接原因是0x00004EF0 根本不是函数结尾，00004E5C处有如下指令，跳出了指定的函数范围
00004E5C 5C E2                       B               loc_5318

JNI_Onload由于0x00004EF0处使用BX              R2      ;
跳转，而目的地被识别为一个函数，导致ida以为这是指令是函数结尾。

根据目前分析真正的结尾是0000544C
需要先写脚本修正这类跳转，再走deobf

**Comment by oMengLvRong** [comment]
感谢回复。这类跳转应该怎样修复？

**Comment by maiyao1988** [comment]
> 感谢回复。这类跳转应该怎样修复？

将这类跳转自动改成b xxx，明确让让ida识到目的地址，但是除了这些混淆，这个样本还加了一些会让那个ida分析出错的虚假块，需要自动改掉，我还在研究当中。

**Comment by maiyao1988** [comment]
需要先执行decms-ob.py,先做一层反混淆，得到的新so再 模拟一次，然后再走deobf.py
[分析链接](https://bbs.pediy.com/thread-258115.htm)

**Comment by oMengLvRong** [comment]
分析很棒。另外作者你有联系方式吗？

**Comment by maiyao1988** [comment]
> 分析很棒。另外作者你有联系方式吗？

13580525545微信
