### ISSUE TITLE
小白问下trace脚本该怎么使用？

### ISSUE THREAD

**Issue by SuperYogurt** [maiyao1988/deobf#2]
blocks_to_trace参数不知道写什么？

**Comment by maiyao1988** [comment]
trace脚本在IDAScripts仓库里面，指定一个函数名，函数的所有指令都会下trace断点，执行到的时候会自动记录下来。

**Comment by SuperYogurt** [comment]
不好意思，可以在详细一点吗？
我现在在ida里运行脚本提示这样的error

File "C:/Users/ASUS/Downloads/deobf-master/deobf/tracer.py", line 112, in <module>
    Tracer(trace_path=path, lib_name=so, start_addr=start, end_addr=end, blocks_to_trace=1)
  File "C:/Users/ASUS/Downloads/deobf-master/deobf/tracer.py", line 59, in __init__
    print(self.__addr2trace)
AttributeError: Tracer instance has no attribute '_Tracer__addr2trace'

**Comment by maiyao1988** [comment]
用这个[脚本](https://github.com/maiyao1988/IDAScripts/blob/master/trace.py)

**Comment by SuperYogurt** [comment]
> 用这个[脚本](https://github.com/maiyao1988/IDAScripts/blob/master/trace.py)

好的，谢谢
